<template>
  <v-container>
    <v-row>
      <h2>カードのサンプル</h2>
    </v-row>
    <v-row>
      <v-col>
        <v-card>
          <v-card-title>カードコンポーネント</v-card-title>
          <v-card-text>
            V-cardコンポーネントは、見出し、テキスト、画像、アクション用に、シンプルなインターフェイスを提供する汎用性の高いコンポーネントです。
          </v-card-text>
          <v-card-actions>
            <v-btn
              color="primary"
              variant="elevated"
            >
              OK
            </v-btn>
            <v-btn
              variant="elevated"
            >
              キャンセル
            </v-btn>
          </v-card-actions>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>